import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import ProductForm from "../components/ProductForm";
import GenerateBill from "../components/GenerateBill";
import { Button } from "@mui/material";
import Link from "next/link";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col md:flex-row">
        <main className="mt-10 w-full flex justify-center items-center">
          <ProductForm />
        </main>
        <main className="mt-10 w-full flex justify-center items-center">
          <GenerateBill />
        </main>
      </div>
      <div className="w-full flex justify-center">
        <Link href="/product">
          <Button className="mx-auto bg-blue-500" variant="contained">
            view Product
          </Button>
        </Link>
      </div>
    </div>
  );
};

export default Home;
